spring.application.name=personalProject

# ===============================
# DATABASE - MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/investment_tracker
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# REDIS
# ===============================
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# PRICE REFRESH
# ===============================
app.price-refresh.fixed-rate-ms=300000

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=${JWT_SECRET}




